### ISSUE TITLE
Plug-and-play plugins

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/rocket#88]
Current plugins require code to actually be committed to ubclaunchpad/rocket. Following #84 and the option for a generic self-hosted Rocket, this won't be a very good experience for plugins.

What if you could actually drop binaries in as plugins?

https://medium.com/learning-the-go-programming-language/writing-modular-go-programs-with-plugins-ec46381ee1a9

> Tucked among the multitude of significant features introduced in Go version 1.8 is a new Go plugin system. This feature let programmers build loosely coupled modular programs using packages compiled as shared object libraries that can be loaded and bound to dynamically at runtime.

Example: https://github.com/vladimirvivien/go-plugin-example

Pretty neat!

**Comment by bfbachmann** [comment]
Yea this looks nice. It could also allow us to enable and disable plugins on the fly. We'd still have to build the image with all the plugin files in it, though.

**Comment by bobheadxi** [comment]
They can be mounted in as well, for any plugins that aren't included in the core `rocket` image. One way might be to mount a config file:

```toml
# rocket.toml
[[plugin]]
    name = "welcome"
    binary = "welcome.so"
    # other settings?
[[plugin]]
    name = "game"
    binary = "game.so"
```

And mount everything:

```bash
sudo docker run -d \
    -v "$(pwd)"/config:/app/plugins \
    -v /binaries:/app/plugins \
    ubclaunchpad/rocket $ARGS
```
